### ISSUE TITLE
api-example.splitwise.com doesn't resolve

### ISSUE THREAD

**Issue by Krinkle** [splitwise/api-example#1]
http://api-example.splitwise.com/ is mentioned from http://dev.splitwise.com/#examples, but the domain doesn't resolve.

**Comment by rofreg** [comment]
Sorry for the trouble! We took down the live API example a few months ago – as a small team, we haven't had the time to maintain it, and we had concerns about running an app on the `splitwise.com` domain that used an outdated, insecure version of Rails. I'll see if we can update http://dev.splitwise.com/#examples to reflect that. Our apologies!

**Comment by satyanash** [comment]
The page still hasn't been updated and points to the dead link.

**Comment by Krinkle** [comment]
See https://github.com/splitwise/api-docs and https://dev.beta.splitwise.com for newer stuff.

Nice work :)
